services:

  redis:
    image: docker.io/redis:8.0
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=Pa55w.rd
    networks:
      - calculator
    volumes:
      - 'redis_data:/data'

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]

  frontend:
    build: ../../container/react-ui
    networks:
      - calculator
    depends_on:
    - redis
    - placement
    ports:
    - 8181:8080

  frontend-dapr:
    image: "daprio/daprd:latest"
    command: [
        "./daprd",
      "--app-id", "frontend",
      "--app-port", "8080",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "/components"
      ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
        - frontend
    network_mode: "service:frontend"


  subtract:
    build: ../../container/csharp
    depends_on:
    - redis
    - placement
    ports:
    - 3000:80
    networks:
      - calculator

  subtract-dapr:
    image: "daprio/daprd:latest"
    command: [
        "./daprd",
      "--app-id", "subtractapp",
      "--app-port", "80",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "/components"
      ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
        - subtract
    network_mode: "service:subtract"

  adder:
    build: ../../container/go
    depends_on:
    - redis
    - placement
    networks:
      - calculator
    environment:
      - APP_PORT=6000
    ports:
    - 6000:6000

  adder-dapr:
    image: "daprio/daprd:latest"
    command: [
        "./daprd",
      "--app-id", "addapp",
      "--app-port", "6000",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "/components"
      ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
        - adder
    network_mode: "service:adder"

  divider:
    build: ../../container/node
    depends_on:
    - redis
    - placement
    networks:
      - calculator
    environment:
      - APP_PORT=4000
    ports:
    - 4000:4000

  divider-dapr:
    image: "daprio/daprd:latest"
    command: [
        "./daprd",
      "--app-id", "divideapp",
      "-app-port", "4000",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "/components"
      ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
        - divider
    network_mode: "service:divider"

  multiplier:
    build: ../../container/python
    depends_on:
    - redis
    - placement
    networks:
      - calculator
    environment:
      - APP_PORT=2000
    ports:
      - 2000:2000

  multiplier-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
     "--app-id", "multiplyapp",
     "--app-port", "2000",
     "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
     "--resources-path", "/components"
     ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - multiplier
    network_mode: "service:multiplier"

networks:
  calculator:

volumes:
  redis_data:
    driver: local
